### PR TITLE
Fix some edge cases in preprocess logic

### PR DESCRIPTION
**Pull request by platinumazure**
Added some new failing tests and fixed the code to ensure the tests pass. I also created a fixture directory to make it easier to add new cases.

### CODE REVIEW

**Review by duhaime — COMMENTED** [review]
@platinumazure Thanks so much for this! My only question is why not call the mocha binary right from the node_modules? I prefer to avoid globally installing modules, so would rather revert to `./node_modules/mocha/bin/mocha ./tests/*.js` in `package.json`. This reversion would also help others who prefer to avoid dependency installation at the system level. What do you think about that?

**Comment by platinumazure** [comment]
When running an npm/yarn script, `./node_modules/.bin` is temporarily
inserted into your PATH at the beginning. So as long as mocha is installed
locally, `yarn test` actually calls the local mocha, not a global one.
Since you have mocha as a devDependency, everything should work just fine.
:smile:

**Comment by platinumazure** [comment]
See https://yarnpkg.com/lang/en/docs/cli/run/ for more details.

**Comment by duhaime** [comment]
Ah, thanks @platinumazure I didn't know that! Thanks again for this PR!

**Pull request merged**
